name: basic_fastapi_ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v5
            - name: installing python
              uses: actions/setup-python@v5
              with:
                   python-version: '3.13'
            - name: installing dependencis
              run: |
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt
            - name: building project
              run: |
                  echo "Building project"
    
    run:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: checkout repository
              uses: actions/checkout@v5
            - name: installing python
              uses: actions/setup-python@v5
              with:
                   python-version: '3.13'
            - name: installing dependencis
              run: |
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt 
            - name: fake error with message
              run: |
                  echo "::error::This is a fake error for testing"
                  exit 1
            - name: building project
              run: |
                  echo "Building project"

    deploy:
        runs-on: ubuntu-latest
        needs: run
        steps:
            - name: checkout repository
              uses: actions/checkout@v5
            - name: installing python
              uses: actions/setup-python@v5
              with:
                   python-version: '3.13'
            - name: installing dependencis
              run: |
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt 
            - name: fake error with message
              run: |
                  echo "::error::This is a fake error for testing"
                  exit 1
            - name: building project
              run: |
                  echo "Building project"